service: prisma-aws-lambda-example
plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules: true

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  profile: personal

functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: handlers/seed.handler
    timeout: 15
    events:
      - http:
          method: GET
          path: /seed
  getUsers:
    handler: handlers/users.handler
    events:
      - http:
          method: GET
          path: /users
  createUser:
    handler: handlers/create-user.handler
    events:
      - http:
          method: POST
          path: /users
  getPosts:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /posts
