service: prisma-aws-lambda-example
package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: "yarn" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Pro

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  profile: personal

functions:
  status:
    handler: src/handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: src/handlers/seed.handler
    timeout: 15
    events:
      - http:
          method: GET
          path: /seed
  getUsers:
    handler: src/handlers/users.handler
    events:
      - http:
          method: GET
          path: /users
  createUser:
    handler: src/handlers/create-user.handler
    events:
      - http:
          method: POST
          path: /users
  getPosts:
    handler: src/handlers/posts.handler
    events:
      - http:
          method: GET
          path: /posts
